'use client'

import { useState, useEffect } from 'react'

function buildReportFilename(): string {
  return `threat-report-${Date.now()}.txt`
}

interface ReportData {
  type: string
  target: string
  timestamp: string
  riskScore?: number
  threatLevel?: string
  verdict?: string
  findings: string[]
  recommendations: string[]
  iocs?: { ips: string[]; domains: string[]; urls: string[]; hashes: string[] }
  raw?: unknown
}

export default function ReportGenerator() {
  const [reportData, setReportData] = useState<ReportData | null>(null)
  const [copied, setCopied] = useState(false)

  useEffect(() => {
    const triage = localStorage.getItem('threatAnalyzer_triageSession')
    const last = localStorage.getItem('threatAnalyzer_lastResult')
    try {
      if (last) setReportData(JSON.parse(last))
      else if (triage) {
        const t = JSON.parse(triage)
        setReportData({
          type: 'TRIAGE',
          target: t.target,
          timestamp: t.timestamp,
          riskScore: t.maxScore,
          threatLevel: t.threatLevel,
          findings: [
            t.email ? `Email: ${t.email.riskScore}/100` : null,
            t.headers ? `Headers: ${t.headers.riskScore}/100` : null,
            t.urlScans?.length ? `${t.urlScans.length} URL scan(s)` : null,
          ].filter(Boolean) as string[],
          recommendations: ['Review full triage session in raw export'],
          raw: t,
        })
      }
    } catch { /* ignore */ }
  }, [])

  const generateReport = () => {
    const data = localStorage.getItem('threatAnalyzer_lastResult')
    if (data) {
      try { setReportData(JSON.parse(data)) } catch {}
    }
  }

  const downloadReport = () => {
    if (!reportData) return
    const text = formatReport(reportData)
    const blob = new Blob([text], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = buildReportFilename()
    a.click()
    URL.revokeObjectURL(url)
  }

  const copyReport = async () => {
    if (!reportData) return
    await navigator.clipboard.writeText(formatReport(reportData))
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  const downloadPDF = () => {
    if (!reportData) return
    const html = buildPDFHtml(reportData)
    const win = window.open('', '_blank')
    if (!win) return
    win.document.write(html)
    win.document.close()
    setTimeout(() => {
      win.print()
    }, 300)
  }

  const formatReport = (d: ReportData): string => {
    const lines: string[] = []
    lines.push('═══════════════════════════════════════════════')
    lines.push('  THREATANALYZER v2.1 — ANALYST REPORT')
    lines.push('═══════════════════════════════════════════════')
    lines.push('')
    lines.push(`Date:     ${new Date(d.timestamp || Date.now()).toLocaleString()}`)
    lines.push(`Type:     ${d.type?.toUpperCase() || 'UNKNOWN'}`)
    lines.push(`Target:   ${d.target || 'N/A'}`)
    lines.push('')
    if (d.riskScore !== undefined) {
      lines.push(`── RISK ASSESSMENT ──`)
      lines.push(`Score:    ${d.riskScore}/100`)
      lines.push(`Level:    ${(d.threatLevel || 'unknown').toUpperCase()}`)
      lines.push('')
    }
    if (d.verdict) {
      lines.push(`── VERDICT ──`)
      lines.push(d.verdict)
      lines.push('')
    }
    if (d.findings?.length > 0) {
      lines.push(`── FINDINGS ──`)
      d.findings.forEach((f, i) => lines.push(`${i + 1}. ${f}`))
      lines.push('')
    }
    if (d.iocs) {
      lines.push(`── INDICATORS OF COMPROMISE ──`)
      if (d.iocs.ips?.length) { lines.push(`IPs:     ${d.iocs.ips.join(', ')}`) }
      if (d.iocs.domains?.length) { lines.push(`Domains: ${d.iocs.domains.join(', ')}`) }
      if (d.iocs.urls?.length) { lines.push(`URLs:    ${d.iocs.urls.join(', ')}`) }
      if (d.iocs.hashes?.length) { lines.push(`Hashes:  ${d.iocs.hashes.join(', ')}`) }
      lines.push('')
    }
    if (d.recommendations?.length > 0) {
      lines.push(`── RECOMMENDATIONS ──`)
      d.recommendations.forEach((r, i) => lines.push(`${i + 1}. ${r}`))
      lines.push('')
    }
    lines.push('═══════════════════════════════════════════════')
    lines.push('  Generated by ThreatAnalyzer v2.0')
    lines.push('═══════════════════════════════════════════════')
    return lines.join('\n')
  }

  const buildPDFHtml = (d: ReportData): string => {
    const riskColor = d.riskScore !== undefined
      ? (d.riskScore >= 70 ? '#e53935' : d.riskScore >= 40 ? '#f59e0b' : '#00a86b')
      : '#666'

    return `<!DOCTYPE html>
<html><head><meta charset="utf-8">
<title>ThreatAnalyzer Report — ${d.target || 'Unknown'}</title>
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: 'Courier New', monospace; background: #fff; color: #1a1a2e; padding: 40px; max-width: 800px; margin: 0 auto; }
  .header { border-bottom: 3px solid #00a86b; padding-bottom: 20px; margin-bottom: 30px; }
  .header h1 { font-size: 24px; color: #00a86b; letter-spacing: 2px; }
  .header .version { font-size: 12px; color: #999; margin-top: 4px; }
  .meta { display: grid; grid-template-columns: 120px 1fr; gap: 8px; margin-bottom: 20px; font-size: 13px; }
  .meta .label { color: #666; font-weight: bold; }
  .meta .value { color: #1a1a2e; word-break: break-all; }
  .risk-box { display: flex; align-items: center; gap: 20px; background: #f8f8f8; border-radius: 8px; padding: 20px; margin-bottom: 20px; border-left: 4px solid ${riskColor}; }
  .risk-score { font-size: 48px; font-weight: bold; color: ${riskColor}; line-height: 1; }
  .risk-info { flex: 1; }
  .risk-level { font-size: 14px; color: ${riskColor}; font-weight: bold; text-transform: uppercase; }
  .section { margin-bottom: 20px; }
  .section h2 { font-size: 12px; color: #00a86b; text-transform: uppercase; letter-spacing: 2px; border-bottom: 1px solid #e0e0e0; padding-bottom: 6px; margin-bottom: 10px; }
  .section ul { list-style: none; padding-left: 0; }
  .section ul li { font-size: 13px; padding: 4px 0; border-bottom: 1px solid #f0f0f0; }
  .ioc-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; font-size: 12px; }
  .ioc-grid div { background: #f8f8f8; padding: 8px 12px; border-radius: 4px; word-break: break-all; }
  .ioc-grid .ioc-label { color: #666; font-weight: bold; margin-bottom: 4px; }
  .footer { border-top: 2px solid #e0e0e0; margin-top: 30px; padding-top: 15px; font-size: 11px; color: #999; text-align: center; }
  @media print { body { padding: 20px; } }
</style>
</head><body>
  <div class="header">
    <h1>THREATANALYZER v2.0</h1>
    <div class="version">Threat Analysis Report — ${new Date(d.timestamp || Date.now()).toLocaleString()}</div>
  </div>

  <div class="meta">
    <div class="label">Type</div><div class="value">${d.type?.toUpperCase() || 'UNKNOWN'}</div>
    <div class="label">Target</div><div class="value">${d.target || 'N/A'}</div>
    <div class="label">Date</div><div class="value">${new Date(d.timestamp || Date.now()).toLocaleString()}</div>
  </div>

  ${d.riskScore !== undefined ? `
  <div class="risk-box">
    <div class="risk-score">${d.riskScore}<span style="font-size:16px;color:#999">/100</span></div>
    <div class="risk-info">
      <div class="risk-level">${(d.threatLevel || 'unknown').toUpperCase()}</div>
      <div style="font-size:12px;color:#666;margin-top:4px">Risk Assessment</div>
    </div>
  </div>` : ''}

  ${d.verdict ? `
  <div class="section">
    <h2>Verdict</h2>
    <div style="font-size:13px;line-height:1.6">${d.verdict}</div>
  </div>` : ''}

  ${d.findings?.length ? `
  <div class="section">
    <h2>Findings</h2>
    <ul>
      ${d.findings.map((f, i) => `<li>${i + 1}. ${f}</li>`).join('')}
    </ul>
  </div>` : ''}

  ${d.iocs ? `
  <div class="section">
    <h2>Indicators of Compromise</h2>
    <div class="ioc-grid">
      ${d.iocs.ips?.length ? `<div><div class="ioc-label">IPs (${d.iocs.ips.length})</div>${d.iocs.ips.join('<br>')}</div>` : ''}
      ${d.iocs.domains?.length ? `<div><div class="ioc-label">Domains (${d.iocs.domains.length})</div>${d.iocs.domains.join('<br>')}</div>` : ''}
      ${d.iocs.urls?.length ? `<div><div class="ioc-label">URLs (${d.iocs.urls.length})</div>${d.iocs.urls.join('<br>')}</div>` : ''}
      ${d.iocs.hashes?.length ? `<div><div class="ioc-label">Hashes (${d.iocs.hashes.length})</div>${d.iocs.hashes.join('<br>')}</div>` : ''}
    </div>
  </div>` : ''}

  ${d.recommendations?.length ? `
  <div class="section">
    <h2>Recommendations</h2>
    <ul>
      ${d.recommendations.map((r, i) => `<li>${i + 1}. ${r}</li>`).join('')}
    </ul>
  </div>` : ''}

  <div class="footer">
    Generated by ThreatAnalyzer v2.0 • ${new Date().toLocaleDateString()}
  </div>
</body></html>`
  }

  return (
    <div className="space-y-4">
      <div className="bg-[#111119] border border-[#1a1a2e] rounded-lg p-4">
        <p className="text-sm text-gray-300 mb-2">Generates a formatted analyst report from your last analysis. Run any analysis in another tab, then come back here.</p>
        <button onClick={generateReport} className="w-full py-2.5 rounded-lg bg-[#00ff88] text-black font-bold text-sm mb-2">
          📄 Generate Report
        </button>
      </div>

      {reportData && (
        <>
          <div className="grid grid-cols-3 gap-2">
            <button
              onClick={copyReport}
              className={`py-2.5 rounded-lg text-xs font-bold uppercase ${copied ? 'bg-[#00ff88]/20 text-[#00ff88]' : 'bg-[#111119] text-gray-400 border border-[#1a1a2e] hover:text-white'}`}
            >
              {copied ? '✓ Copied' : '📋 Copy'}
            </button>
            <button
              onClick={downloadReport}
              className="py-2.5 rounded-lg text-xs font-bold uppercase bg-[#111119] text-gray-400 border border-[#1a1a2e] hover:text-white"
            >
              💾 .txt
            </button>
            <button
              onClick={downloadPDF}
              className="py-2.5 rounded-lg text-xs font-bold uppercase bg-[#111119] text-gray-400 border border-[#1a1a2e] hover:text-white"
            >
              📕 PDF
            </button>
          </div>

          <pre className="bg-[#0a0a0f] border border-[#00ff88]/30 rounded-lg p-4 text-xs font-mono text-[#00ff88] whitespace-pre-wrap overflow-x-auto">
            {formatReport(reportData)}
          </pre>
        </>
      )}

      {!reportData && (
        <div className="bg-[#111119] border border-[#1a1a2e] rounded-lg p-6 text-center">
          <span className="text-3xl">📄</span>
          <p className="text-sm text-gray-400 mt-2">No analysis data yet. Run an analysis in another tab first.</p>
        </div>
      )}
    </div>
  )
}